%assoc (subrs, "drop", ↪︎xdrop)
%assoc (subrs, "dup", ↪︎xdup)
%assoc (subrs, "negate", ↪︎xnegate)
%assoc (subrs, "emit", ↪︎xemit)
%assoc (subrs, "cr", ↪︎xcr)
%assoc (subrs, ".", ↪︎xdot)
%assoc (subrs, ".s", ↪︎xdots)
%assoc (subrs, "+", ↪︎xadd)
%assoc (subrs, "*", ↪︎xmul)
%assoc (subrs, "swap", ↪︎xswap)
%assoc (subrs, "-",    ↪︎xsub)
%assoc (subrs, "/",    ↪︎xdiv)
%assoc (subrs, "word", ↪︎xword)
%assoc (subrs, '"', ↪︎xquote, 1)
%assoc (subrs, '."', ↪︎xdotquote)
%assoc (subrs, "(", ↪︎xcomment, 1)
%assoc (subrs, "(literal)", doliteral)
%assoc (subrs, "branch", ↪︎xbranch)
%assoc (subrs, "0branch", ↪︎x0branch)
%assoc (subrs, "if", ↪︎xif, 1)
%assoc (subrs, "else", ↪︎xelse, 1)
%assoc (subrs, "then", ↪︎xthen, 1)
%assoc (subrs, "constant", ↪︎xconst)
%assoc (subrs, "create", ↪︎xcreate)
%assoc (subrs, ",", ↪︎xcomma)
%assoc (subrs, "variable", ↪︎xvar)
%assoc (subrs, "dump", ↪︎xdump)
%assoc (subrs, "@", ↪︎xstore)
%assoc (subrs, "!", ↪︎xstore)
%assoc (subrs, "bye",  ↪︎xbye)
%assoc (subrs, "find", ↪︎xfind)
%assoc (subrs, "'", ↪︎xtick)
%assoc (subrs, "None", ↪︎pushNone)
%assoc (subrs, "words", ↪︎xwords)    
%assoc (subrs, "execute", ↪︎xexecute)
%assoc (subrs, ":", ↪︎xcolon)
%assoc (subrs, ";", ↪︎xsemi, 1)
%assoc (subrs, "interpret", ↪︎xinterpret)
