
⌈ left-over from simple.py, where we used a Python dict to lookup words, but,
  in this version (fcomp), we create a dictionary as a linked list in the traditional manner 
defvar subrs ⇐ %freshdict
%assoc (subrs, "drop", ↪︎xdrop)
%assoc (subrs, "dup", ↪︎xdup)
%assoc (subrs, "negate", ↪︎xnegate)
%assoc (subrs, "emit", ↪︎xemit)
%assoc (subrs, "cr", ↪︎xcr)
%assoc (subrs, ".", ↪︎xdot)
%assoc (subrs, ".s", ↪︎xdots)
%assoc (subrs, "+", ↪︎xadd)
%assoc (subrs, "*", ↪︎xmul)
%assoc (subrs, "swap", ↪︎xswap)
%assoc (subrs, "-",    ↪︎xsub)
%assoc (subrs, "/",    ↪︎xdiv)
%assoc (subrs, "word", ↪︎xword)
%assoc (subrs, '"', ↪︎xquote)
%assoc (subrs, '."', ↪︎xdotquote)
%assoc (subrs, "(", ↪︎xcomment)
%assoc (subrs, "(literal)", doliteral)
%assoc (subrs, "branch", ↪︎xbranch)
%assoc (subrs, "0branch", ↪︎x0branch)
%assoc (subrs, "if", ↪︎xif)
%assoc (subrs, "else", ↪︎xelse)
%assoc (subrs, "then", ↪︎xthen)
%assoc (subrs, "constant", ↪︎xconst)
%assoc (subrs, "create", ↪︎xcreate)
%assoc (subrs, ",", ↪︎xcomma)
%assoc (subrs, "variable", ↪︎xvar)
%assoc (subrs, "dump", ↪︎xdump)
%assoc (subrs, "@", ↪︎xstore)
%assoc (subrs, "!", ↪︎xstore)
%assoc (subrs, "bye",  ↪︎xbye)
%assoc (subrs, "find", ↪︎xfind)
%assoc (subrs, "'", ↪︎xtick)
%assoc (subrs, "None", ↪︎pushNone)
%assoc (subrs, "words", ↪︎xwords)    
%assoc (subrs, "execute", ↪︎xexecute)
%assoc (subrs, ":", ↪︎xcolon)
%assoc (subrs, ";", ↪︎xsemi)
%assoc (subrs, "interpret", ↪︎xinterpret)
⌉
